-- Textos reales (con acentos) que ya estaban escritos en las paginas de la web.
-- Objetivo: que el panel muestre lo mismo que se ve, y se pueda editar desde ahi.
update contenido_secciones set titulo=$q$Atletismo en pista$q$, dirigido_a=$q$Federado y popular · temporada 2026-27$q$, descripcion=$q$El corazón del club: velocidad, vallas, medio fondo, fondo, saltos y lanzamientos, cada disciplina con su técnica y su forma de sufrir. Hay quien viene a bajar su 400 y quien busca el Campeonato de España; en los dos casos hay planificación individual detrás.$q$ where seccion=$s$competicion$s$;
update contenido_secciones set titulo=$q$Running$q$, dirigido_a=$q$Adultos · asfalto, cross y trail$q$, descripcion=$q$Dos grupos según el momento en el que estés: uno para coger el hábito y disfrutar del kilómetro, otro para buscar marca. En los dos hay entrenador en pista y plan escrito cada semana.$q$ where seccion=$s$running$s$;
update contenido_secciones set titulo=$q$Natación$q$, dirigido_a=$q$Adultos · todos los niveles$q$, descripcion=$q$Grupos por nivel y sesiones dirigidas en el Tossal y Vía Parque: técnica de los cuatro estilos, series de fondo, velocidad y preparación de competición. En verano, piscina de 50 metros y aguas abiertas los sábados.$q$ where seccion=$s$natacion$s$;
update contenido_secciones set titulo=$q$Triatlón$q$, dirigido_a=$q$Natación · ciclismo · carrera$q$, descripcion=$q$Dominar tres disciplinas y saber encadenarlas: nadar, montar y correr gestionando el esfuerzo para que las piernas respondan al bajar de la bici. La sección nació en 2011 con cinco socios y hoy pasa de cincuenta.$q$ where seccion=$s$triatlon$s$;
update contenido_secciones set titulo=$q$Montaña$q$, dirigido_a=$q$Senderismo y trail · todas las edades$q$, descripcion=$q$Rutas por la Serra de la Marina, el Maigmó, el Puig Campana y las sierras que rodean Alicante. No hay ritmo obligatorio ni competición: hay rutas para todos los niveles, desde paseos familiares hasta travesías exigentes.$q$ where seccion=$s$montana$s$;
update contenido_secciones set titulo=$q$El Cubo$q$, dirigido_a=$q$Entrenamiento funcional$q$, descripcion=$q$El gimnasio del club, junto a la pista: fuerza, core y prevención en grupos de doce. Nadadores, corredores y triatletas comparten sala y cada uno lleva su progresión.$q$ where seccion=$s$cubo$s$;
update contenido_secciones set titulo=$q$Escuela de atletismo$q$, dirigido_a=$q$Escuela · temporada 2026-27$q$, descripcion=$q$Iniciación y desarrollo del atletismo de los 3 a los 17 años. Correr, saltar y lanzar en forma de juego en las categorías pequeñas, y especialización cuando toca.$q$ where seccion=$s$escuela$s$;
update contenido_secciones set titulo=$q$Escuela de natación$q$, dirigido_a=$q$Escuela · 6 a 15 años$q$, descripcion=$q$Aprendizaje y perfeccionamiento en las piscinas del Tossal y Vía Parque, con grupos reducidos y la opción de competir en federado si al niño le apetece.$q$ where seccion=$s$escuela-natacion$s$;
update contenido_secciones set titulo=$q$Atletismo municipal$q$, dirigido_a=$q$Programa de Deportes Alicante$q$, descripcion=$q$Escuela deportiva municipal que gestiona el club dentro del programa del Ayuntamiento de Alicante. La inscripción y el precio los fija Deportes Alicante; los entrenadores y la metodología son los mismos de la escuela del club.$q$ where seccion=$s$escuela-municipal$s$;
update contenido_secciones set titulo=$q$XII Campus de verano$q$, dirigido_a=$q$Del 29 de junio al 31 de julio · 3 a 16 años$q$, descripcion=$q$Atletismo, multideporte, pádel, natación, juegos de agua, gymkanas, talleres y una excursión cada semana. Todo con enfoque lúdico: el objetivo es que hagan deporte pasándolo bien.$q$ where seccion=$s$campus$s$;
update contenido_secciones set titulo=$q$Instalaciones$q$, dirigido_a=$q$Dónde entrenamos$q$, descripcion=$q$Cuatro sedes repartidas por la ciudad. Todas son municipales salvo El Cubo, que es del club y está dentro del estadio.$q$ where seccion=$s$instalaciones$s$;
